"""
Downloads the web fonts the portal uses and writes a local stylesheet for them.

Both families are variable fonts, so one file per subset covers every weight the
design uses. Asking for discrete weights instead returns the same file once per
weight - that is how this ended up as 22 downloads of 5 distinct files the first
time round.

Only the subsets this site can render are kept: latin and latin-ext for the
interface, devanagari for the Hindi in the government strip and anything Bhashini
translates into Devanagari. Cyrillic, Greek and Vietnamese are dropped; nothing on
this portal sets type in them.
"""
import os, re, urllib.request

SRC = ('https://fonts.googleapis.com/css2?family=Inter:wght@100..900'
       '&family=Noto+Sans+Devanagari:wght@100..900&display=swap')
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36')
KEEP = {'latin', 'latin-ext', 'devanagari'}
OUT = os.path.join('public', 'assets', 'fonts')


def get(url, binary=False):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode('utf-8')


css = get(SRC)
os.makedirs(OUT, exist_ok=True)
blocks = re.findall(r'/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})', css, re.S)

rules, total = [], 0
for subset, block in blocks:
    if subset not in KEEP:
        continue

    family = re.search(r"font-family: '([^']+)'", block).group(1)
    weight = re.search(r'font-weight: ([\d ]+);', block).group(1).strip()
    url = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)
    unicode_range = re.search(r'unicode-range: ([^;]+);', block).group(1)

    name = f"{family.lower().replace(' ', '-')}-{subset}.woff2"
    path = os.path.join(OUT, name)
    with open(path, 'wb') as fh:
        fh.write(get(url, binary=True))
    total += os.path.getsize(path)

    rules.append(
        "@font-face {\n"
        f"  font-family: '{family}';\n"
        "  font-style: normal;\n"
        f"  font-weight: {weight};\n"
        "  font-display: swap;\n"
        f"  src: url('/assets/fonts/{name}') format('woff2');\n"
        f"  unicode-range: {unicode_range};\n"
        "}"
    )

header = """/*
 * Self-hosted web fonts.
 *
 * The portal used to pull these from fonts.googleapis.com on every visit, which
 * told a third party who was reading a government site and left the page's type
 * at the mercy of a network the ministry does not control. They are served from
 * this origin instead.
 *
 * Both families are variable, so one file per subset carries every weight the
 * design uses. unicode-range means a visitor reading English never downloads the
 * Devanagari file, and vice versa.
 *
 * Generated by scripts/fetch-fonts.py - do not hand-edit.
 * Inter and Noto Sans Devanagari are under the SIL Open Font License 1.1, which
 * travels with them in public/assets/fonts/OFL.txt.
 */

"""

with open(os.path.join('src', 'styles', '_fonts.scss'), 'w', encoding='utf-8', newline='') as fh:
    fh.write((header + '\n\n'.join(rules) + '\n').replace('\n', '\r\n'))

print(f'{len(rules)} faces, {len(rules)} files, {total / 1024:.0f} kB')
