import {
  AGENCIES,
  DOCUMENT_CATEGORIES,
  ICON_OPTIONS,
  LEAN_LEVELS,
  PARTNER_TYPES,
  PROGRAMME_STATUSES,
  PROGRAMME_TYPES,
  ResourceConfig,
  SelectOption,
} from './resource.config';

type Row = Record<string, unknown> & { id: number };

/**
 * Configuration for every resource served by the shared management screen.
 * Adding a new simple resource is a matter of adding an entry here and a route.
 */

export const BANNERS: ResourceConfig<Row> = {
  path: 'banners',
  title: 'Home page banners',
  singular: 'banner',
  icon: 'layers',
  lead: 'Slides in the hero carousel at the top of the home page.',
  note: 'Alternative text is mandatory: it is what a screen reader announces in place of the image.',
  sortable: true,
  searchPlaceholder: 'Search banners by title…',
  columns: [
    { header: 'Image', field: 'imageUrl', kind: 'image', width: '110px' },
    { header: 'Title', field: 'title', subField: 'subtitle' },
    { header: 'Eyebrow', field: 'eyebrow', kind: 'badge', width: '200px' },
    { header: 'Active', field: 'isActive', kind: 'boolean', width: '90px' },
  ],
  fields: [
    { name: 'eyebrow', label: 'Eyebrow', type: 'text', maxLength: 200, hint: 'Small label above the headline.' },
    { name: 'title', label: 'Headline', type: 'text', required: true, maxLength: 300 },
    {
      name: 'highlightedTitle',
      label: 'Highlighted second line',
      type: 'text',
      maxLength: 300,
      hint: 'Rendered in the accent colour beneath the headline.',
    },
    { name: 'subtitle', label: 'Lead paragraph', type: 'textarea', maxLength: 800, rows: 3 },
    { name: 'imageUrl', label: 'Background image', type: 'image', required: true, section: 'Media' },
    { name: 'mobileImageUrl', label: 'Mobile image', type: 'image', section: 'Media' },
    {
      name: 'altText',
      label: 'Alternative text',
      type: 'text',
      required: true,
      maxLength: 300,
      section: 'Media',
      hint: 'Describe the image for screen reader users.',
      full: true,
    },
    { name: 'primaryButtonText', label: 'Primary button text', type: 'text', section: 'Buttons' },
    { name: 'primaryButtonUrl', label: 'Primary button link', type: 'url', section: 'Buttons' },
    { name: 'secondaryButtonText', label: 'Secondary button text', type: 'text', section: 'Buttons' },
    { name: 'secondaryButtonUrl', label: 'Secondary button link', type: 'url', section: 'Buttons' },
    { name: 'sortOrder', label: 'Order', type: 'number', section: 'Scheduling' },
    { name: 'isActive', label: 'Active', type: 'boolean', defaultValue: true, section: 'Scheduling' },
    { name: 'startsAt', label: 'Show from', type: 'date', section: 'Scheduling' },
    { name: 'endsAt', label: 'Show until', type: 'date', section: 'Scheduling' },
  ],
};

export const FAQS: ResourceConfig<Row> = {
  path: 'faqs',
  title: 'Frequently asked questions',
  singular: 'question',
  icon: 'help-circle',
  lead: 'Questions shown in the accordion on the FAQs page, grouped by topic.',
  sortable: true,
  searchPlaceholder: 'Search questions and answers…',
  pageSize: 25,
  columns: [
    { header: 'Status', field: 'status', kind: 'status', width: '130px' },
    { header: 'Question', field: 'question' },
    { header: 'Category', field: 'category', kind: 'badge', width: '190px' },
    { header: 'Featured', field: 'isFeatured', kind: 'boolean', width: '100px' },
  ],
  fields: [
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'Published', label: 'Published' },
        { value: 'Draft', label: 'Draft' },
        { value: 'Archived', label: 'Archived' },
      ],
      hint: 'Draft and Archived hide the record from the public site without deleting it.',
    },
    { name: 'question', label: 'Question', type: 'textarea', required: true, maxLength: 600, rows: 2 },
    {
      name: 'answer',
      label: 'Answer',
      type: 'html',
      required: true,
      rows: 8,
      hint: 'HTML is allowed. Scripts and unsafe markup are stripped on save.',
    },
    {
      name: 'category',
      label: 'Category',
      type: 'text',
      maxLength: 120,
      defaultValue: 'General',
      hint: 'Questions are grouped by this value on the public page.',
    },
    { name: 'sortOrder', label: 'Order', type: 'number' },
    { name: 'isFeatured', label: 'Featured', type: 'boolean', hint: 'Highlight this question' },
  ],
};

export const DOCUMENTS: ResourceConfig<Row> = {
  path: 'documents',
  title: 'Documents',
  singular: 'document',
  icon: 'download',
  lead: 'Guidelines, brochures, circulars, formats and presentations available for download.',
  note: 'Upload the file in the Media library first, then paste its URL here.',
  sortable: true,
  searchPlaceholder: 'Search documents…',
  columns: [
    { header: 'Status', field: 'status', kind: 'status', width: '130px' },
    { header: 'Title', field: 'title', subField: 'description' },
    { header: 'Category', field: 'categoryName', kind: 'badge', width: '180px' },
    { header: 'Type', field: 'fileType', kind: 'badge', width: '90px' },
    { header: 'Size', field: 'fileSizeDisplay', width: '100px' },
    { header: 'Downloads', field: 'downloadCount', kind: 'number', width: '110px' },
  ],
  fields: [
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'Published', label: 'Published' },
        { value: 'Draft', label: 'Draft' },
        { value: 'Archived', label: 'Archived' },
      ],
      hint: 'Draft and Archived hide the record from the public site without deleting it.',
    },
    { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 400 },
    { name: 'category', label: 'Category', type: 'select', required: true, options: DOCUMENT_CATEGORIES },
    { name: 'description', label: 'Description', type: 'textarea', maxLength: 1000, rows: 3 },
    { name: 'fileUrl', label: 'File URL', type: 'text', required: true, section: 'File', full: true },
    {
      name: 'fileType',
      label: 'File type',
      type: 'select',
      required: true,
      section: 'File',
      defaultValue: 'PDF',
      options: ['PDF', 'DOC', 'DOCX', 'XLS', 'XLSX', 'PPT', 'PPTX', 'CSV', 'ZIP'].map((v) => ({
        value: v,
        label: v,
      })),
    },
    {
      name: 'fileSizeBytes',
      label: 'File size (bytes)',
      type: 'number',
      section: 'File',
      hint: 'Shown next to the download link.',
    },
    { name: 'language', label: 'Language', type: 'text', section: 'File', defaultValue: 'English' },
    { name: 'version', label: 'Version', type: 'text', section: 'File' },
    { name: 'documentDate', label: 'Document date', type: 'date', section: 'File' },
    { name: 'sortOrder', label: 'Order', type: 'number', section: 'Display' },
    {
      name: 'isFeatured',
      label: 'Featured',
      type: 'boolean',
      section: 'Display',
      hint: 'Show on the home page',
    },
  ],
};

export const STATISTICS: ResourceConfig<Row> = {
  path: 'statistics',
  title: 'Portal statistics',
  singular: 'statistic',
  icon: 'trending-up',
  lead: 'The counter strip on the home page.',
  note: 'Where a source key is set, the value is refreshed automatically from the transactional LEAN database.',
  sortable: true,
  searchPlaceholder: 'Search statistics…',
  columns: [
    { header: 'Label', field: 'label' },
    { header: 'Value', field: 'value', kind: 'number', width: '130px' },
    { header: 'Icon', field: 'icon', kind: 'badge', width: '150px' },
    { header: 'Active', field: 'isActive', kind: 'boolean', width: '90px' },
  ],
  fields: [
    { name: 'label', label: 'Label', type: 'text', required: true, maxLength: 200 },
    { name: 'value', label: 'Value', type: 'number', required: true },
    { name: 'prefix', label: 'Prefix', type: 'text', maxLength: 20 },
    { name: 'suffix', label: 'Suffix', type: 'text', maxLength: 20, hint: 'For example a plus sign.' },
    { name: 'icon', label: 'Icon', type: 'select', options: ICON_OPTIONS },
    { name: 'linkUrl', label: 'Links to', type: 'text' },
    {
      name: 'sourceQueryKey',
      label: 'Source key',
      type: 'text',
      maxLength: 100,
      hint: 'Leave blank to maintain this figure manually.',
    },
    { name: 'sortOrder', label: 'Order', type: 'number' },
    { name: 'isActive', label: 'Active', type: 'boolean', defaultValue: true },
  ],
};

export const LOGIN_PORTALS: ResourceConfig<Row> = {
  path: 'login-portals',
  title: 'Login portals',
  singular: 'portal',
  icon: 'login',
  lead: 'Stakeholder sign-in and registration tiles on the home page.',
  note: 'Relative URLs such as /VerifyUdyam/Register are resolved against the transactional LEAN application.',
  sortable: true,
  searchPlaceholder: 'Search portals…',
  columns: [
    { header: 'Title', field: 'title', subField: 'description' },
    { header: 'Audience', field: 'audience', kind: 'badge', width: '170px' },
    { header: 'Colour', field: 'accentColor', kind: 'colour', width: '80px' },
    { header: 'Active', field: 'isActive', kind: 'boolean', width: '90px' },
  ],
  fields: [
    { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 250 },
    { name: 'audience', label: 'Audience', type: 'text', maxLength: 150 },
    { name: 'description', label: 'Description', type: 'textarea', maxLength: 600, rows: 2 },
    { name: 'icon', label: 'Icon', type: 'select', options: ICON_OPTIONS },
    { name: 'accentColor', label: 'Accent colour', type: 'color' },
    { name: 'loginUrl', label: 'Login URL', type: 'text', section: 'Links' },
    { name: 'loginText', label: 'Login button text', type: 'text', section: 'Links', defaultValue: 'Login Now' },
    { name: 'registerUrl', label: 'Register URL', type: 'text', section: 'Links' },
    { name: 'registerText', label: 'Register button text', type: 'text', section: 'Links' },
    { name: 'sortOrder', label: 'Order', type: 'number', section: 'Display' },
    { name: 'isActive', label: 'Active', type: 'boolean', defaultValue: true, section: 'Display' },
    {
      name: 'openInNewTab',
      label: 'Open in a new tab',
      type: 'boolean',
      defaultValue: true,
      section: 'Display',
    },
  ],
};

export const SCHEME_LEVELS: ResourceConfig<Row> = {
  path: 'scheme-levels',
  title: 'Scheme levels',
  singular: 'level',
  icon: 'award',
  lead: 'The LEAN Pledge and the Bronze, Silver and Gold implementation tiers.',
  sortable: true,
  searchPlaceholder: 'Search levels…',
  columns: [
    { header: 'Name', field: 'name', subField: 'tagline' },
    { header: 'Tier', field: 'level', kind: 'badge', width: '140px' },
    { header: 'Badge', field: 'badgeLabel', kind: 'badge', width: '140px' },
    { header: 'Colour', field: 'accentColor', kind: 'colour', width: '80px' },
  ],
  fields: [
    { name: 'level', label: 'Tier', type: 'select', required: true, options: LEAN_LEVELS },
    { name: 'name', label: 'Name', type: 'text', required: true, maxLength: 150 },
    { name: 'badgeLabel', label: 'Badge label', type: 'text', maxLength: 60, hint: 'Bronze, Silver, Gold…' },
    { name: 'tagline', label: 'Tagline', type: 'text', maxLength: 300 },
    { name: 'description', label: 'Description', type: 'html', rows: 6 },
    {
      name: 'deliverables',
      label: 'Deliverables',
      type: 'lines',
      rows: 6,
      hint: 'One per line. Rendered as a tick list on the level card.',
      section: 'Detail',
    },
    { name: 'feeStructure', label: 'Cost to the MSME', type: 'text', maxLength: 500, section: 'Detail' },
    { name: 'duration', label: 'Typical duration', type: 'text', maxLength: 100, section: 'Detail' },
    { name: 'certificateImageUrl', label: 'Certificate image', type: 'image', section: 'Detail' },
    { name: 'iconUrl', label: 'Icon image', type: 'image', section: 'Display' },
    { name: 'accentColor', label: 'Accent colour', type: 'color', section: 'Display' },
    { name: 'sortOrder', label: 'Order', type: 'number', section: 'Display' },
    { name: 'isActive', label: 'Active', type: 'boolean', defaultValue: true, section: 'Display' },
  ],
};

export const SCHEME_COMPONENTS: ResourceConfig<Row> = {
  path: 'scheme-components',
  title: 'Scheme components',
  singular: 'component',
  icon: 'layers',
  lead: 'The six components of the scheme, shown as an icon grid on the home page.',
  sortable: true,
  searchPlaceholder: 'Search components…',
  columns: [
    { header: 'Title', field: 'title', subField: 'shortDescription' },
    { header: 'Icon', field: 'icon', kind: 'badge', width: '160px' },
    { header: 'Links to', field: 'linkUrl', width: '220px' },
  ],
  fields: [
    { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 250 },
    { name: 'icon', label: 'Icon', type: 'select', options: ICON_OPTIONS },
    {
      name: 'shortDescription',
      label: 'Short description',
      type: 'textarea',
      maxLength: 500,
      rows: 2,
      hint: 'Shown on the home page tile.',
    },
    { name: 'description', label: 'Full description', type: 'html', rows: 6 },
    { name: 'linkUrl', label: 'Links to', type: 'text' },
    { name: 'sortOrder', label: 'Order', type: 'number' },
    { name: 'isActive', label: 'Active', type: 'boolean', defaultValue: true },
  ],
};

export const TESTIMONIALS: ResourceConfig<Row> = {
  path: 'testimonials',
  title: 'Success stories',
  singular: 'story',
  icon: 'quote',
  lead: 'MSME success stories shown in the carousel on the home page.',
  sortable: true,
  searchPlaceholder: 'Search stories…',
  columns: [
    { header: 'Status', field: 'status', kind: 'status', width: '130px' },
    { header: 'Enterprise', field: 'unitName', subField: 'quote' },
    { header: 'Location', field: 'location', width: '190px' },
    { header: 'Level', field: 'achievedLevel', kind: 'badge', width: '150px' },
  ],
  fields: [
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'Published', label: 'Published' },
        { value: 'Draft', label: 'Draft' },
        { value: 'Archived', label: 'Archived' },
      ],
      hint: 'Draft and Archived hide the record from the public site without deleting it.',
    },
    { name: 'unitName', label: 'Enterprise', type: 'text', required: true, maxLength: 300 },
    { name: 'personName', label: 'Person', type: 'text', maxLength: 200 },
    { name: 'designation', label: 'Designation', type: 'text', maxLength: 200 },
    { name: 'location', label: 'Location', type: 'text', maxLength: 200 },
    { name: 'sector', label: 'Sector', type: 'text', maxLength: 200 },
    { name: 'achievedLevel', label: 'Level achieved', type: 'select', options: LEAN_LEVELS },
    { name: 'quote', label: 'Quote', type: 'textarea', required: true, maxLength: 2000, rows: 5 },
    {
      name: 'impactHighlight',
      label: 'Impact highlight',
      type: 'text',
      maxLength: 300,
      hint: 'A single headline outcome, shown as a pill under the quote.',
      section: 'Detail',
    },
    { name: 'photoUrl', label: 'Photograph', type: 'image', section: 'Detail' },
    { name: 'videoUrl', label: 'Video URL', type: 'url', section: 'Detail' },
    { name: 'sortOrder', label: 'Order', type: 'number', section: 'Detail' },
  ],
};

export const PARTNERS: ResourceConfig<Row> = {
  path: 'partners',
  title: 'Partners & links',
  singular: 'partner',
  icon: 'building',
  lead: 'Implementation agencies, industry associations, OEMs, consultant organisations and useful links.',
  sortable: true,
  searchPlaceholder: 'Search partners…',
  pageSize: 25,
  columns: [
    { header: 'Name', field: 'name', subField: 'description' },
    { header: 'Type', field: 'type', kind: 'badge', width: '210px' },
    { header: 'State', field: 'state', width: '150px' },
  ],
  fields: [
    { name: 'type', label: 'Type', type: 'select', required: true, options: PARTNER_TYPES },
    { name: 'name', label: 'Name', type: 'text', required: true, maxLength: 400 },
    { name: 'shortName', label: 'Short name', type: 'text', maxLength: 100 },
    { name: 'registrationNumber', label: 'Registration number', type: 'text', maxLength: 100 },
    { name: 'description', label: 'Description', type: 'html', rows: 4 },
    { name: 'websiteUrl', label: 'Website', type: 'url', section: 'Contact' },
    { name: 'contactUrl', label: 'Contact page', type: 'url', section: 'Contact' },
    { name: 'email', label: 'E-mail', type: 'email', section: 'Contact' },
    {
      name: 'enquiryEmail',
      label: 'Enquiries inbox',
      type: 'email',
      section: 'Enquiries',
      hint:
        'Where enquiries choosing this agency are sent. Falls back to the e-mail above, ' +
        'and then to the site-wide address. Never shown on the site.',
    },
    {
      name: 'enquiryFormUrl',
      label: 'Own enquiry form',
      type: 'text',
      maxLength: 500,
      section: 'Enquiries',
      hint:
        'Optional. A Zoho (or other) form embed address. When set, choosing this agency ' +
        'shows their form instead of the built-in one. Each agency can have its own.',
    },
    { name: 'phone', label: 'Telephone', type: 'text', maxLength: 60, section: 'Contact' },
    { name: 'address', label: 'Address', type: 'textarea', maxLength: 600, rows: 2, section: 'Contact' },
    { name: 'city', label: 'City', type: 'text', maxLength: 120, section: 'Contact' },
    { name: 'state', label: 'State', type: 'text', maxLength: 120, section: 'Contact' },
    { name: 'logoUrl', label: 'Logo', type: 'image', section: 'Display' },
    { name: 'sortOrder', label: 'Order', type: 'number', section: 'Display' },
    { name: 'isActive', label: 'Active', type: 'boolean', defaultValue: true, section: 'Display' },
    { name: 'isFeatured', label: 'Featured', type: 'boolean', section: 'Display' },
  ],
};

export const PROGRAMMES: ResourceConfig<Row> = {
  path: 'programmes',
  title: 'Programmes',
  singular: 'programme',
  icon: 'calendar',
  lead: 'Awareness programmes and training for assessors and consultants.',
  searchPlaceholder: 'Search by title, code, state or district…',
  pageSize: 25,
  columns: [
    { header: 'Status', field: 'status', kind: 'status', width: '130px' },
    { header: 'Programme', field: 'title', subField: 'programmeCode' },
    { header: 'Type', field: 'programmeType', kind: 'badge', width: '190px' },
    { header: 'State', field: 'state', width: '150px' },
    { header: 'Starts', field: 'startDate', kind: 'date', width: '130px' },
    { header: 'Status', field: 'programmeStatus', kind: 'status', width: '160px' },
  ],
  fields: [
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      options: [
        { value: 'Published', label: 'Published' },
        { value: 'Draft', label: 'Draft' },
        { value: 'Archived', label: 'Archived' },
      ],
      hint: 'Draft and Archived hide the record from the public site without deleting it.',
    },
    { name: 'programmeCode', label: 'Programme code', type: 'text', required: true, maxLength: 60 },
    { name: 'programmeType', label: 'Type', type: 'select', required: true, options: PROGRAMME_TYPES },
    { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 400 },
    { name: 'agency', label: 'Agency', type: 'select', options: AGENCIES },
    { name: 'description', label: 'Description', type: 'html', rows: 4 },
    { name: 'state', label: 'State / UT', type: 'text', maxLength: 120, section: 'Where and when' },
    { name: 'district', label: 'District', type: 'text', maxLength: 120, section: 'Where and when' },
    { name: 'venue', label: 'Venue', type: 'textarea', maxLength: 500, rows: 2, section: 'Where and when' },
    { name: 'startDate', label: 'Start date', type: 'date', required: true, section: 'Where and when' },
    { name: 'endDate', label: 'End date', type: 'date', section: 'Where and when' },
    { name: 'registeredCount', label: 'Registered', type: 'number', section: 'Registration' },
    { name: 'capacity', label: 'Capacity', type: 'number', section: 'Registration' },
    { name: 'registrationUrl', label: 'Registration URL', type: 'url', section: 'Registration' },
    {
      name: 'programmeStatus',
      label: 'Status',
      type: 'select',
      required: true,
      options: PROGRAMME_STATUSES,
      defaultValue: 'Upcoming',
      section: 'Registration',
    },
  ],
};

export const BENEFITS: ResourceConfig<Row> = {
  path: 'benefits',
  title: 'Benefits / Incentives',
  singular: 'benefit',
  icon: 'award',
  lead:
    'The cards in the Benefits / Incentives band on the home page. Each one names a source of ' +
    'support and links to the page that sets out what it offers.',
  sortable: true,
  searchPlaceholder: 'Search benefits…',
  pageSize: 25,
  columns: [
    { header: 'Title', field: 'title', subField: 'subtitle' },
    { header: 'Links to', field: 'linkUrl' },
    { header: 'Order', field: 'sortOrder', width: '90px' },
  ],
  fields: [
    { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 200 },
    {
      name: 'subtitle',
      label: 'Description',
      type: 'text',
      maxLength: 300,
      hint: 'The line under the title, e.g. "Incentives by States and Union Territories".',
    },
    {
      name: 'linkUrl',
      label: 'Links to',
      type: 'text',
      maxLength: 500,
      hint: 'A page on this site such as /benefits-incentives/states-uts, or a full web address.',
    },
    { name: 'linkText', label: 'Button text', type: 'text', maxLength: 60, hint: 'Defaults to "View".' },
    { name: 'openInNewTab', label: 'Opens in a new tab', type: 'boolean' },
    {
      name: 'imageUrl',
      label: 'Artwork',
      type: 'image',
      section: 'Display',
      hint: 'Optional. Used instead of the icon below when set.',
    },
    {
      name: 'icon',
      label: 'Icon',
      type: 'text',
      maxLength: 80,
      section: 'Display',
      hint: 'Used when no artwork is uploaded, e.g. building, map, handshake, award.',
    },
    { name: 'sortOrder', label: 'Order', type: 'number', section: 'Display' },
    { name: 'isActive', label: 'Active', type: 'boolean', defaultValue: true, section: 'Display' },
  ],
};

const INCENTIVE_CATEGORIES: SelectOption[] = [
  { value: 'Ministry', label: 'Ministry of MSME' },
  { value: 'States', label: 'States / UTs' },
  { value: 'Financial', label: 'Financial institutions' },
  { value: 'Other', label: 'Other ministries and organisations' },
];

export const INCENTIVES: ResourceConfig<Row> = {
  path: 'incentives',
  title: 'Incentives',
  singular: 'incentive',
  icon: 'certificate',
  lead:
    'The entries listed under Benefits / Incentives. Each names the body offering it, what it is ' +
    'worth, who to contact and where the notification can be read.',
  sortable: true,
  searchPlaceholder: 'Search by title, issuer or state…',
  pageSize: 25,
  columns: [
    { header: 'Incentive', field: 'title', subField: 'issuerName' },
    { header: 'Category', field: 'category', kind: 'badge', width: '160px' },
    { header: 'Level', field: 'level', width: '130px' },
    { header: 'State', field: 'state', width: '150px' },
  ],
  fields: [
    { name: 'category', label: 'Category', type: 'select', required: true, options: INCENTIVE_CATEGORIES },
    { name: 'title', label: 'Title', type: 'text', required: true, maxLength: 400, full: true },
    { name: 'description', label: 'Description', type: 'html', rows: 5, full: true },
    {
      name: 'level',
      label: 'Scheme level',
      type: 'select',
      options: LEAN_LEVELS,
      hint: 'Leave empty when it applies at every level.',
    },
    {
      name: 'state',
      label: 'State / UT',
      type: 'text',
      maxLength: 120,
      hint: 'Only for an incentive notified by one state. Leave empty otherwise.',
    },
    { name: 'issuerName', label: 'Offered by', type: 'text', maxLength: 300, section: 'Who offers it' },
    { name: 'issuerLogoUrl', label: 'Logo', type: 'image', section: 'Who offers it' },
    { name: 'contactName', label: 'Contact name', type: 'text', maxLength: 300, section: 'Who to contact' },
    { name: 'contactEmail', label: 'Contact e-mail', type: 'email', section: 'Who to contact' },
    { name: 'contactPhone', label: 'Contact telephone', type: 'text', maxLength: 120, section: 'Who to contact' },
    { name: 'document1Url', label: 'Document 1', type: 'text', maxLength: 500, section: 'Documents and claiming' },
    { name: 'document1Label', label: 'Document 1 label', type: 'text', maxLength: 120, section: 'Documents and claiming' },
    { name: 'document2Url', label: 'Document 2', type: 'text', maxLength: 500, section: 'Documents and claiming' },
    { name: 'document2Label', label: 'Document 2 label', type: 'text', maxLength: 120, section: 'Documents and claiming' },
    {
      name: 'videoUrl',
      label: 'Film',
      type: 'text',
      maxLength: 500,
      section: 'Documents and claiming',
      hint: 'A YouTube or Vimeo address. Shown as a player inside the entry.',
    },
    {
      name: 'availUrl',
      label: 'Where to claim it',
      type: 'text',
      maxLength: 500,
      section: 'Documents and claiming',
      hint: 'No button is shown when this is empty.',
    },
    { name: 'availLabel', label: 'Button text', type: 'text', maxLength: 60, section: 'Documents and claiming', hint: 'Defaults to "Avail".' },
    { name: 'sortOrder', label: 'Order', type: 'number', section: 'Display' },
    { name: 'isActive', label: 'Active', type: 'boolean', defaultValue: true, section: 'Display' },
  ],
};

/** Lookup used by the admin route that renders a resource by its route segment. */
export const RESOURCE_REGISTRY: Record<string, ResourceConfig<Row>> = {
  banners: BANNERS,
  faqs: FAQS,
  documents: DOCUMENTS,
  statistics: STATISTICS,
  benefits: BENEFITS,
  incentives: INCENTIVES,
  'login-portals': LOGIN_PORTALS,
  'scheme-levels': SCHEME_LEVELS,
  'scheme-components': SCHEME_COMPONENTS,
  testimonials: TESTIMONIALS,
  partners: PARTNERS,
  programmes: PROGRAMMES,
};
